### ISSUE TITLE
The name of executable

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags-snap#1]
The current snap uploaded to the store installs the executable name `universal-ctags.ctags`.

This causes problems, in that `universal-ctags` considers filenames ending with `.ctags` are "optfiles" for defining a command line based parser.

Please rename the installed executable to `universal-ctags`.

Also, create an automatic alias of `ctags`. Don't forget to remove the README section about manually creating that alias.

**Comment by tartley** [comment]
I speculate that this is because two different snaps cannot provide the same executable name. The "ctags" executable name is already associated with "exuberant-ctags", so we had to choose something else, and "SNAPNAME.EXENAME" is the store's default fallback.

This explanation is slightly puzzling, in that exuberant-ctags doesn't have a snap, as far as I can tell, so I'm not sure how that association got made in the store.

I believe there is a mechanism by which executable names can be transferred from one snap to another, by agreement of all parties. I'll go read about it...

**Comment by masatake** [comment]
> We can change the name to 'universal-ctags' or 'u-ctags' as suggested.

Yes. Privately, I'm using the name, `u-ctags`.

**Comment by tartley** [comment]
@masatake Ideally, would we want the snap to install the executable name 'ctags'? (then it matches the executable name installed by compiling source, or installing the deb.)

Shoud I contact the exuberant author, to ask whether they might release a snap themselves? Or do they bless universal as the official new version of 'ctags'?

**Comment by masatake** [comment]
I would like to make clear why I open this issue.
I don't want the snap to use ".ctags" extension for the executable.
As I wrote, ".ctags" extension is for configuration files (optlib files) for ctags.
I introduced this conversion.

About the issue about file name extension, any name is o.k. 

However, ctags executable shipped from exuberant-ctags project is so popular.
So naming ctags to the executable installed via snap can be trouble.
u-ctags or universal-ctags will be good.

On Fedora I'm using daily, there is a feature named "alternative".
I don't know its history but maybe it comes from Debina.
https://manpages.debian.org/wheezy/dpkg/update-alternatives.8.en.html
I think we can use this if we are making a package. I'm not sure it is applicable to snap.

About this topic, you don't have to think about exuberant-ctags. It seems that the project is not active.
(If it is active, we don't have to run this project :-).

**Comment by tartley** [comment]
> So naming ctags to the executable installed via snap can be trouble.

This doesn't quite make sense to me, because installing from source, and installing the .deb, both provide a 'ctags' executable.

My personal inclination is that we should match that behavior, so that a person switching between the .deb and the snap doesn't break their tools that call ctags. (and in the same way, a person switching from exuberant-ctags to universal-ctags should not have to rewrite their tools that call ctags.)

People who are trying to install exuberant or universal simultaneously are a very small subset of users, and will have to know how to manage their PATH or aliases in order to call the correct executable. I think this is a reasonable expectation for users who have chosen a more advanced scenario.

Reading more about the snapstore, I think the way I'll implement this is for the default executable to be 'universal-ctags' (because this is easy to do, since it matches our snap name), and then add a snap alias of 'ctags' This will somehow provide an alias for users, but if it conflicts with something (like exuberant) then users are able to choose which one the alias should refer to.

**Comment by masatake** [comment]
I don't have strong option about this topic because I use only /home/yamato/var/ctags-github/ctags :-P.

**Comment by tartley** [comment]
A request has been put into the snap store for us to be assigned the executable name alias "ctags", and looks like it's on track to be approved in a week.

This won't conflict with other snaps which want a "ctags" alias (currently there are none) - users can install both and are able to choose which snap is invoked by the alias.

Users who install both the universal snap and the exuberant apt package will find exuberant to be foremost on the PATH.

**Comment by tartley** [comment]
The 'ctags' alias has now been granted by the snap store.

So now, the executable installed by this snap can either be invoked as 'universal-ctags' or 'ctags'.
